---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: satvikvm/spe_mini_project:latest
        source: pull
    - name: Start docker container
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calculator satvikvm/spe_mini_project
